import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useState } from "react";
import { RiRadioButtonFill } from "react-icons/ri";
import Header from "../../components/home/Header";
import project1Image from "public/assets/images/german-stories-theme.png";
import { FaCss3 } from "react-icons/fa";
const ProjectLessonGenerator: React.FC = () => {
    return (
        <div className={`main`}>
            <Head>
                <title>Listen German Stories Project</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header isHomePage={false} />
            <div className="w-screen h-[30vh] lg:h-[40vh] relative">
                <div className="absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/70 z-10"></div>
                <Image src={project1Image} className="absolute z-1" fill={true} objectFit="cover" alt="Listen German Stories" />
                <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
                    <h2 className="py-2">Listen German Stories</h2>
                    <h3>NextJS / TailwindCSS</h3>
                </div>
            </div>
            <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-12 gap-8 py-14 px-8 md:px-20 dark:bg-gray-900 dark:text-gray-100">
                <div className="col-span-4 md:col-span-8">
                    <p className="text-3xl md:text-4xl">Listen German Stories</p>
                    <p className="text-xl md:text-2xl my-2">Overview</p>
                    <p className="my-5">
                        The Listen German Stories is a Next.js web app for listening to audio stories in German. It allows users to browse stories by category and level and play them directly on the
                        site. Stories are played using a custom HTML5 audio player. The stories and the images were generated by ChatGPT.
                    </p>
                    <Link href="https://listengermanstories.vercel.app" target="_blank">
                        <button className="button px-8 py-2 mt-4 mr-8">Demo</button>
                    </Link>
                    <Link href="https://github.com/irvingzamora28/listengermanstories" target="_blank">
                        <button className="button px-8 py-2 mt-4">Code</button>
                    </Link>
                </div>
                <div className="col-span-4 md:col-span-4 shadow-xl shadow-gray-400 dark:shadow-gray-800 rounded-xl p-4">
                    <div className="p-2">
                        <p>Technologies Used</p>
                        <div className="grid grid-cols-2 md:grid-cols-1">
                            <p className="flex items-center text-gray-600 dark:text-gray-400 py-2">
                                <RiRadioButtonFill className="mr-2" /> NextJS
                            </p>
                            <p className="flex items-center text-gray-600 dark:text-gray-400 py-2">
                                <RiRadioButtonFill className="mr-2" /> Web Speech API
                            </p>
                            <p className="flex items-center text-gray-600 dark:text-gray-400 py-2">
                                <FaCss3 className="mr-2" /> TailwindCSS
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-12 gap-8 md:mb-0 px-8 md:px-20 dark:bg-gray-900 dark:text-gray-100">
                <div className="col-span-12">
                    <Link href={"/#projects"}>
                        <p className="underline cursor-pointer">Back to Projects</p>
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default ProjectLessonGenerator;
